# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedKeyParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('param_type', models.CharField(choices=[('header', 'Header Parameter'), ('query', 'Query Parameter')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AuthMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_type', models.CharField(choices=[('basic', 'Basic Authentication'), ('key', 'Key Authentication')], max_length=16)),
                ('priority', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='BaseCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicAuthCredentials',
            fields=[
                ('basecredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_auth.BaseCredentials')),
                ('username', models.CharField(max_length=255)),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('api_auth.basecredentials',),
        ),
        migrations.CreateModel(
            name='KeyCredentials',
            fields=[
                ('basecredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_auth.BaseCredentials')),
                ('key', fernet_fields.fields.EncryptedCharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=('api_auth.basecredentials',),
        ),
    ]
