# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_auto_20170307_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicauthcredentials',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
