# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_api_consumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRateLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('call_amount', models.PositiveIntegerField()),
                ('time_amount', models.PositiveIntegerField()),
                ('time_unit', models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('months', 'months'), ('years', 'years')], max_length=8)),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.API')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddressRateLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('call_amount', models.PositiveIntegerField()),
                ('time_amount', models.PositiveIntegerField()),
                ('time_unit', models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('months', 'months'), ('years', 'years')], max_length=8)),
                ('ip_address', models.GenericIPAddressField()),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.API')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ipaddressratelimit',
            unique_together=set([('api', 'ip_address')]),
        ),
        migrations.AlterUniqueTogether(
            name='consumerratelimit',
            unique_together=set([('api', 'consumer')]),
        ),
    ]
