# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170307_1940'),
        ('traffic_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSizeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('max_kilobytes', models.PositiveIntegerField()),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.API')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
