# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0002_api_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consumer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.API'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('plan', 'consumer')]),
        ),
    ]
