# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_api_consumer'),
        ('api_logging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogentry',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.API'),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Consumer'),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_logging.RequestLogEntry'),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_logging.ResponseLogEntry'),
        ),
    ]
