# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_logging', '0002_auto_20170307_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogentry',
            name='latency',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
