# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_logging', '0003_apilogentry_latency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilogentry',
            options={},
        ),
    ]
