# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('subdomain', models.CharField(max_length=64, unique=True)),
                ('proxy_protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', max_length=10)),
                ('proxy_host', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'APIs',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(max_length=128, null=True)),
                ('custom_id', models.CharField(max_length=128, null=True)),
                ('source', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
