# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170307_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={},
        ),
    ]
